# Generated by Django 5.2.7 on 2025-10-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(default=list)),
                ('symptoms', models.JSONField(default=list)),
                ('remedies', models.JSONField(default=list)),
                ('severity', models.CharField(default='medium', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
